### PR TITLE
Feature Auth pages

### PR DESCRIPTION
**Pull request by OmKakatkar**
## Adds Login, Sign Up and Forgot Password Screens
* Please ignore files for Landing, Home, Category and Rules page, they are added in a different PR

image
image
image

### CODE REVIEW

**Review by romabulani — APPROVED** [review]
Code is modular and readable
Suggestions:
- If possible, host the images on cloudinary or other image hosting platform, it will help in fast loading
- In label in react, there is `htmlFor` attribute and not `for`

**Review by lomesshh — APPROVED** [review]
code is modular
UI looks clean and Beautiful

Looks good to merge

**Comment by OmKakatkar** [comment]
> Code is modular and readable Suggestions:
> 
> * If possible, host the images on cloudinary or other image hosting platform, it will help in fast loading
> * In label in react, there is `htmlFor` attribute and not `for`

Thanks for the suggestions.
* The images will be hosted in a future PR
* Since, this is not a react project, `for` is the correct usage here.

**Comment by romabulani** [comment]
> > Code is modular and readable Suggestions:
> > 
> > * If possible, host the images on cloudinary or other image hosting platform, it will help in fast loading
> > * In label in react, there is `htmlFor` attribute and not `for`
> 
> Thanks for the suggestions.
> 
> * The images will be hosted in a future PR
> * Since, this is not a react project, `for` is the correct usage here.

Sorry, my bad, I thought its jsx file.

**Pull request merged**
