### PR TITLE
Feature Quiz Result Pages

### PR DESCRIPTION
**Pull request by OmKakatkar**
## Adds Quiz and Result Pages
* Please ignore the Landing, Home, Auth, Category and Rule Pages, they are add in a different PR

image
image
image

### CODE REVIEW

**Review by thegeorgenikhil — APPROVED** [review]
Good Folder structure and Good Class Namings
Clean UI!

Suggestion: instead of naming the font-size variable `fs-h3/fs-h2`, being little more descriptive would make the class name easily understandable.

**Comment by OmKakatkar** [comment]
> Good Folder structure and Good Class Namings Clean UI!
> 
> Suggestion: instead of naming the font-size variable `fs-h3/fs-h2`, being little more descriptive would make the class name easily understandable.

Thanks for the suggestions.
The variables are coming directly from the component library. And while deciding the names, I followed a naming convention of --
What is the variable for? font-size : fs
What is the value representing? A font size similar to h2 and h3 : h2/h3
Finally deciding upon `fs-h2` and `fs-h3`

**Review by shrey27 — APPROVED** [review]
Naming convention is good
UI also looks clean
PR is ready to merge

**Review by lomesshh — APPROVED** [review]
Clean code , UI also looks pretty cool
Looks good to merge

**Pull request merged**
